CREATE TABLE IF NOT EXISTS collection (
    pk_collection_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS file (
    pk_file_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    collection_id INTEGER NOT NULL REFERENCES collection(pk_collection_id),
    is_folder BOOLEAN NOT NULL DEFAULT TRUE,
    parent_id INTEGER REFERENCES file(pk_file_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);