// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function SelectAllCollections():Promise<api.ApiResponse___posto_app_models_Collection_>;
