// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectAllCollections() {
  return window['go']['api']['CollectionApi']['SelectAllCollections']();
}

export function SelectAllCollectionsWithFiles() {
  return window['go']['api']['CollectionApi']['SelectAllCollectionsWithFiles']();
}

export function SelectAllCollectionsWithFilesNested() {
  return window['go']['api']['CollectionApi']['SelectAllCollectionsWithFilesNested']();
}
