// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repositories} from '../models';
import {api} from '../models';

export function CreateFileOrFolder(arg1:repositories.FileCreationParam):Promise<api.ApiResponse_int_>;
