// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFileOrFolder(arg1) {
  return window['go']['api']['FileApi']['CreateFileOrFolder'](arg1);
}

export function GetRequestData(arg1) {
  return window['go']['api']['FileApi']['GetRequestData'](arg1);
}

export function UpdateFile(arg1, arg2) {
  return window['go']['api']['FileApi']['UpdateFile'](arg1, arg2);
}
