// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repositories} from '../models';
import {api} from '../models';

export function CreateFileOrFolder(arg1:repositories.FileCreationParam):Promise<api.ApiResponse_int_>;

export function GetRequestData(arg1:number):Promise<api.ApiResponse_posto_app_repositories_FileRequestData_>;

export function UpdateFile(arg1:number,arg2:repositories.FileRequestData):Promise<api.ApiResponse_bool_>;
